// gRPC contract: 确定性节点 (build / coverage / oracle)
// 由 Python 编排器同步调用；Go 侧 internal/service/grpc_server.go 实现，
// 复用 internal/compiler、internal/coverage、internal/oracle，不改裁决逻辑。
//
// 设计要点：
// - 这三个 service 是确定性节点，绝不调用 agent（plan FR-002）。
// - CheckerMetadataService 暴露 SSOT 元数据只读视图，gRPC 与 MCP 共读同一份
//   internal/oracle/metadata.go（research R4）。
// - 覆盖率只在 CoverageService.Measure 强制测出（FR-022）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: oracle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verdict int32

const (
	Verdict_VERDICT_PASS           Verdict = 0
	Verdict_VERDICT_FAIL           Verdict = 1
	Verdict_VERDICT_NOT_APPLICABLE Verdict = 2
	Verdict_VERDICT_ERROR          Verdict = 3
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_PASS",
		1: "VERDICT_FAIL",
		2: "VERDICT_NOT_APPLICABLE",
		3: "VERDICT_ERROR",
	}
	Verdict_value = map[string]int32{
		"VERDICT_PASS":           0,
		"VERDICT_FAIL":           1,
		"VERDICT_NOT_APPLICABLE": 2,
		"VERDICT_ERROR":          3,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_oracle_proto_enumTypes[0].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_oracle_proto_enumTypes[0]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

type Seed struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source           string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // C 源码
	ParentId         string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	SelectedCheckers []string               `protobuf:"bytes,4,rep,name=selected_checkers,json=selectedCheckers,proto3" json:"selected_checkers,omitempty"` // checker ID 集（不含 ISA, FR-013）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Seed) Reset() {
	*x = Seed{}
	mi := &file_oracle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seed) ProtoMessage() {}

func (x *Seed) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seed.ProtoReflect.Descriptor instead.
func (*Seed) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{0}
}

func (x *Seed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Seed) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Seed) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Seed) GetSelectedCheckers() []string {
	if x != nil {
		return x.SelectedCheckers
	}
	return nil
}

type InvariantResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // 如 INV-SP-L01
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"` // static | dynamic
	Verdict       Verdict                `protobuf:"varint,3,opt,name=verdict,proto3,enum=defuzz.core.v1.Verdict" json:"verdict,omitempty"`
	Evidence      string                 `protobuf:"bytes,4,opt,name=evidence,proto3" json:"evidence,omitempty"`                                                                       // 人读
	Detail        map[string]string      `protobuf:"bytes,5,rep,name=detail,proto3" json:"detail,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 机读
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                                                           // 仅 NA / Error
	Isa           string                 `protobuf:"bytes,7,opt,name=isa,proto3" json:"isa,omitempty"`                                                                                 // 该结果对应的 ISA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvariantResult) Reset() {
	*x = InvariantResult{}
	mi := &file_oracle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvariantResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvariantResult) ProtoMessage() {}

func (x *InvariantResult) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvariantResult.ProtoReflect.Descriptor instead.
func (*InvariantResult) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{1}
}

func (x *InvariantResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InvariantResult) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *InvariantResult) GetVerdict() Verdict {
	if x != nil {
		return x.Verdict
	}
	return Verdict_VERDICT_PASS
}

func (x *InvariantResult) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

func (x *InvariantResult) GetDetail() map[string]string {
	if x != nil {
		return x.Detail
	}
	return nil
}

func (x *InvariantResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InvariantResult) GetIsa() string {
	if x != nil {
		return x.Isa
	}
	return ""
}

type BuildCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckerId     string                 `protobuf:"bytes,1,opt,name=checker_id,json=checkerId,proto3" json:"checker_id,omitempty"`
	Isa           string                 `protobuf:"bytes,2,opt,name=isa,proto3" json:"isa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildCell) Reset() {
	*x = BuildCell{}
	mi := &file_oracle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildCell) ProtoMessage() {}

func (x *BuildCell) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildCell.ProtoReflect.Descriptor instead.
func (*BuildCell) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{2}
}

func (x *BuildCell) GetCheckerId() string {
	if x != nil {
		return x.CheckerId
	}
	return ""
}

func (x *BuildCell) GetIsa() string {
	if x != nil {
		return x.Isa
	}
	return ""
}

type BuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          *Seed                  `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Cells         []*BuildCell           `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"` // 已展开的编译矩阵
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildRequest) Reset() {
	*x = BuildRequest{}
	mi := &file_oracle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildRequest) ProtoMessage() {}

func (x *BuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildRequest.ProtoReflect.Descriptor instead.
func (*BuildRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{3}
}

func (x *BuildRequest) GetSeed() *Seed {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *BuildRequest) GetCells() []*BuildCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type BuildArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *BuildCell             `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	BinaryPath    string                 `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"` // 编译失败时填（R8：跳过后续, 不崩溃）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildArtifact) Reset() {
	*x = BuildArtifact{}
	mi := &file_oracle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildArtifact) ProtoMessage() {}

func (x *BuildArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildArtifact.ProtoReflect.Descriptor instead.
func (*BuildArtifact) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{4}
}

func (x *BuildArtifact) GetCell() *BuildCell {
	if x != nil {
		return x.Cell
	}
	return nil
}

func (x *BuildArtifact) GetBinaryPath() string {
	if x != nil {
		return x.BinaryPath
	}
	return ""
}

func (x *BuildArtifact) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildArtifact) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifacts     []*BuildArtifact       `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildResponse) Reset() {
	*x = BuildResponse{}
	mi := &file_oracle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildResponse) ProtoMessage() {}

func (x *BuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildResponse.ProtoReflect.Descriptor instead.
func (*BuildResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{5}
}

func (x *BuildResponse) GetArtifacts() []*BuildArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type CoverageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Artifacts       []*BuildArtifact       `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	CumulativeState []byte                 `protobuf:"bytes,2,opt,name=cumulative_state,json=cumulativeState,proto3" json:"cumulative_state,omitempty"` // 传入上轮累积（编排器从 state 取）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CoverageRequest) Reset() {
	*x = CoverageRequest{}
	mi := &file_oracle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageRequest) ProtoMessage() {}

func (x *CoverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageRequest.ProtoReflect.Descriptor instead.
func (*CoverageRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{6}
}

func (x *CoverageRequest) GetArtifacts() []*BuildArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *CoverageRequest) GetCumulativeState() []byte {
	if x != nil {
		return x.CumulativeState
	}
	return nil
}

type CoverageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CumulativeState []byte                 `protobuf:"bytes,1,opt,name=cumulative_state,json=cumulativeState,proto3" json:"cumulative_state,omitempty"` // 更新后累积
	DeltaJson       string                 `protobuf:"bytes,2,opt,name=delta_json,json=deltaJson,proto3" json:"delta_json,omitempty"`                   // 本轮增量（反馈 agent 只读 diff, R6）
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CoverageResponse) Reset() {
	*x = CoverageResponse{}
	mi := &file_oracle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageResponse) ProtoMessage() {}

func (x *CoverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageResponse.ProtoReflect.Descriptor instead.
func (*CoverageResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{7}
}

func (x *CoverageResponse) GetCumulativeState() []byte {
	if x != nil {
		return x.CumulativeState
	}
	return nil
}

func (x *CoverageResponse) GetDeltaJson() string {
	if x != nil {
		return x.DeltaJson
	}
	return ""
}

type OracleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          *Seed                  `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Artifacts     []*BuildArtifact       `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OracleRequest) Reset() {
	*x = OracleRequest{}
	mi := &file_oracle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleRequest) ProtoMessage() {}

func (x *OracleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleRequest.ProtoReflect.Descriptor instead.
func (*OracleRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{8}
}

func (x *OracleRequest) GetSeed() *Seed {
	if x != nil {
		return x.Seed
	}
	return nil
}

func (x *OracleRequest) GetArtifacts() []*BuildArtifact {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type OracleResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Results  []*InvariantResult     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Violated bool                   `protobuf:"varint,2,opt,name=violated,proto3" json:"violated,omitempty"` // 任一 Fail → true（FR-021, R8）
	// 违反时附确定性证据，供最小化分支（FR-025）
	FailingChecker string `protobuf:"bytes,3,opt,name=failing_checker,json=failingChecker,proto3" json:"failing_checker,omitempty"`
	FailingIsa     string `protobuf:"bytes,4,opt,name=failing_isa,json=failingIsa,proto3" json:"failing_isa,omitempty"`
	Evidence       string `protobuf:"bytes,5,opt,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OracleResponse) Reset() {
	*x = OracleResponse{}
	mi := &file_oracle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OracleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OracleResponse) ProtoMessage() {}

func (x *OracleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OracleResponse.ProtoReflect.Descriptor instead.
func (*OracleResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{9}
}

func (x *OracleResponse) GetResults() []*InvariantResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *OracleResponse) GetViolated() bool {
	if x != nil {
		return x.Violated
	}
	return false
}

func (x *OracleResponse) GetFailingChecker() string {
	if x != nil {
		return x.FailingChecker
	}
	return ""
}

func (x *OracleResponse) GetFailingIsa() string {
	if x != nil {
		return x.FailingIsa
	}
	return ""
}

func (x *OracleResponse) GetEvidence() string {
	if x != nil {
		return x.Evidence
	}
	return ""
}

type CheckerMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ApplicableIsas []string               `protobuf:"bytes,2,rep,name=applicable_isas,json=applicableIsas,proto3" json:"applicable_isas,omitempty"`
	Mode           string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`         // single | differential
	Cost           string                 `protobuf:"bytes,4,opt,name=cost,proto3" json:"cost,omitempty"`         // cheap | expensive
	Category       string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"` // static | dynamic
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckerMetadata) Reset() {
	*x = CheckerMetadata{}
	mi := &file_oracle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckerMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckerMetadata) ProtoMessage() {}

func (x *CheckerMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckerMetadata.ProtoReflect.Descriptor instead.
func (*CheckerMetadata) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{10}
}

func (x *CheckerMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckerMetadata) GetApplicableIsas() []string {
	if x != nil {
		return x.ApplicableIsas
	}
	return nil
}

func (x *CheckerMetadata) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CheckerMetadata) GetCost() string {
	if x != nil {
		return x.Cost
	}
	return ""
}

func (x *CheckerMetadata) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListCheckerMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckerMetadataRequest) Reset() {
	*x = ListCheckerMetadataRequest{}
	mi := &file_oracle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckerMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckerMetadataRequest) ProtoMessage() {}

func (x *ListCheckerMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckerMetadataRequest.ProtoReflect.Descriptor instead.
func (*ListCheckerMetadataRequest) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{11}
}

type ListCheckerMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checkers      []*CheckerMetadata     `protobuf:"bytes,1,rep,name=checkers,proto3" json:"checkers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCheckerMetadataResponse) Reset() {
	*x = ListCheckerMetadataResponse{}
	mi := &file_oracle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCheckerMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCheckerMetadataResponse) ProtoMessage() {}

func (x *ListCheckerMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_oracle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCheckerMetadataResponse.ProtoReflect.Descriptor instead.
func (*ListCheckerMetadataResponse) Descriptor() ([]byte, []int) {
	return file_oracle_proto_rawDescGZIP(), []int{12}
}

func (x *ListCheckerMetadataResponse) GetCheckers() []*CheckerMetadata {
	if x != nil {
		return x.Checkers
	}
	return nil
}

var File_oracle_proto protoreflect.FileDescriptor

const file_oracle_proto_rawDesc = "" +
	"\n" +
	"\foracle.proto\x12\x0edefuzz.core.v1\"x\n" +
	"\x04Seed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12+\n" +
	"\x11selected_checkers\x18\x04 \x03(\tR\x10selectedCheckers\"\xb6\x02\n" +
	"\x0fInvariantResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x121\n" +
	"\averdict\x18\x03 \x01(\x0e2\x17.defuzz.core.v1.VerdictR\averdict\x12\x1a\n" +
	"\bevidence\x18\x04 \x01(\tR\bevidence\x12C\n" +
	"\x06detail\x18\x05 \x03(\v2+.defuzz.core.v1.InvariantResult.DetailEntryR\x06detail\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x10\n" +
	"\x03isa\x18\a \x01(\tR\x03isa\x1a9\n" +
	"\vDetailEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\tBuildCell\x12\x1d\n" +
	"\n" +
	"checker_id\x18\x01 \x01(\tR\tcheckerId\x12\x10\n" +
	"\x03isa\x18\x02 \x01(\tR\x03isa\"i\n" +
	"\fBuildRequest\x12(\n" +
	"\x04seed\x18\x01 \x01(\v2\x14.defuzz.core.v1.SeedR\x04seed\x12/\n" +
	"\x05cells\x18\x02 \x03(\v2\x19.defuzz.core.v1.BuildCellR\x05cells\"\x8f\x01\n" +
	"\rBuildArtifact\x12-\n" +
	"\x04cell\x18\x01 \x01(\v2\x19.defuzz.core.v1.BuildCellR\x04cell\x12\x1f\n" +
	"\vbinary_path\x18\x02 \x01(\tR\n" +
	"binaryPath\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"L\n" +
	"\rBuildResponse\x12;\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1d.defuzz.core.v1.BuildArtifactR\tartifacts\"y\n" +
	"\x0fCoverageRequest\x12;\n" +
	"\tartifacts\x18\x01 \x03(\v2\x1d.defuzz.core.v1.BuildArtifactR\tartifacts\x12)\n" +
	"\x10cumulative_state\x18\x02 \x01(\fR\x0fcumulativeState\"\\\n" +
	"\x10CoverageResponse\x12)\n" +
	"\x10cumulative_state\x18\x01 \x01(\fR\x0fcumulativeState\x12\x1d\n" +
	"\n" +
	"delta_json\x18\x02 \x01(\tR\tdeltaJson\"v\n" +
	"\rOracleRequest\x12(\n" +
	"\x04seed\x18\x01 \x01(\v2\x14.defuzz.core.v1.SeedR\x04seed\x12;\n" +
	"\tartifacts\x18\x02 \x03(\v2\x1d.defuzz.core.v1.BuildArtifactR\tartifacts\"\xcd\x01\n" +
	"\x0eOracleResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.defuzz.core.v1.InvariantResultR\aresults\x12\x1a\n" +
	"\bviolated\x18\x02 \x01(\bR\bviolated\x12'\n" +
	"\x0ffailing_checker\x18\x03 \x01(\tR\x0efailingChecker\x12\x1f\n" +
	"\vfailing_isa\x18\x04 \x01(\tR\n" +
	"failingIsa\x12\x1a\n" +
	"\bevidence\x18\x05 \x01(\tR\bevidence\"\x8e\x01\n" +
	"\x0fCheckerMetadata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fapplicable_isas\x18\x02 \x03(\tR\x0eapplicableIsas\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\tR\x04cost\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"\x1c\n" +
	"\x1aListCheckerMetadataRequest\"Z\n" +
	"\x1bListCheckerMetadataResponse\x12;\n" +
	"\bcheckers\x18\x01 \x03(\v2\x1f.defuzz.core.v1.CheckerMetadataR\bcheckers*\\\n" +
	"\aVerdict\x12\x10\n" +
	"\fVERDICT_PASS\x10\x00\x12\x10\n" +
	"\fVERDICT_FAIL\x10\x01\x12\x1a\n" +
	"\x16VERDICT_NOT_APPLICABLE\x10\x02\x12\x11\n" +
	"\rVERDICT_ERROR\x10\x032T\n" +
	"\fBuildService\x12D\n" +
	"\x05Build\x12\x1c.defuzz.core.v1.BuildRequest\x1a\x1d.defuzz.core.v1.BuildResponse2_\n" +
	"\x0fCoverageService\x12L\n" +
	"\aMeasure\x12\x1f.defuzz.core.v1.CoverageRequest\x1a .defuzz.core.v1.CoverageResponse2Y\n" +
	"\rOracleService\x12H\n" +
	"\aAnalyze\x12\x1d.defuzz.core.v1.OracleRequest\x1a\x1e.defuzz.core.v1.OracleResponse2\x88\x01\n" +
	"\x16CheckerMetadataService\x12n\n" +
	"\x13ListCheckerMetadata\x12*.defuzz.core.v1.ListCheckerMetadataRequest\x1a+.defuzz.core.v1.ListCheckerMetadataResponseB3Z1github.com/zjy-dev/de-fuzz/internal/service/pb;pbb\x06proto3"

var (
	file_oracle_proto_rawDescOnce sync.Once
	file_oracle_proto_rawDescData []byte
)

func file_oracle_proto_rawDescGZIP() []byte {
	file_oracle_proto_rawDescOnce.Do(func() {
		file_oracle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)))
	})
	return file_oracle_proto_rawDescData
}

var file_oracle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_oracle_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_oracle_proto_goTypes = []any{
	(Verdict)(0),                        // 0: defuzz.core.v1.Verdict
	(*Seed)(nil),                        // 1: defuzz.core.v1.Seed
	(*InvariantResult)(nil),             // 2: defuzz.core.v1.InvariantResult
	(*BuildCell)(nil),                   // 3: defuzz.core.v1.BuildCell
	(*BuildRequest)(nil),                // 4: defuzz.core.v1.BuildRequest
	(*BuildArtifact)(nil),               // 5: defuzz.core.v1.BuildArtifact
	(*BuildResponse)(nil),               // 6: defuzz.core.v1.BuildResponse
	(*CoverageRequest)(nil),             // 7: defuzz.core.v1.CoverageRequest
	(*CoverageResponse)(nil),            // 8: defuzz.core.v1.CoverageResponse
	(*OracleRequest)(nil),               // 9: defuzz.core.v1.OracleRequest
	(*OracleResponse)(nil),              // 10: defuzz.core.v1.OracleResponse
	(*CheckerMetadata)(nil),             // 11: defuzz.core.v1.CheckerMetadata
	(*ListCheckerMetadataRequest)(nil),  // 12: defuzz.core.v1.ListCheckerMetadataRequest
	(*ListCheckerMetadataResponse)(nil), // 13: defuzz.core.v1.ListCheckerMetadataResponse
	nil,                                 // 14: defuzz.core.v1.InvariantResult.DetailEntry
}
var file_oracle_proto_depIdxs = []int32{
	0,  // 0: defuzz.core.v1.InvariantResult.verdict:type_name -> defuzz.core.v1.Verdict
	14, // 1: defuzz.core.v1.InvariantResult.detail:type_name -> defuzz.core.v1.InvariantResult.DetailEntry
	1,  // 2: defuzz.core.v1.BuildRequest.seed:type_name -> defuzz.core.v1.Seed
	3,  // 3: defuzz.core.v1.BuildRequest.cells:type_name -> defuzz.core.v1.BuildCell
	3,  // 4: defuzz.core.v1.BuildArtifact.cell:type_name -> defuzz.core.v1.BuildCell
	5,  // 5: defuzz.core.v1.BuildResponse.artifacts:type_name -> defuzz.core.v1.BuildArtifact
	5,  // 6: defuzz.core.v1.CoverageRequest.artifacts:type_name -> defuzz.core.v1.BuildArtifact
	1,  // 7: defuzz.core.v1.OracleRequest.seed:type_name -> defuzz.core.v1.Seed
	5,  // 8: defuzz.core.v1.OracleRequest.artifacts:type_name -> defuzz.core.v1.BuildArtifact
	2,  // 9: defuzz.core.v1.OracleResponse.results:type_name -> defuzz.core.v1.InvariantResult
	11, // 10: defuzz.core.v1.ListCheckerMetadataResponse.checkers:type_name -> defuzz.core.v1.CheckerMetadata
	4,  // 11: defuzz.core.v1.BuildService.Build:input_type -> defuzz.core.v1.BuildRequest
	7,  // 12: defuzz.core.v1.CoverageService.Measure:input_type -> defuzz.core.v1.CoverageRequest
	9,  // 13: defuzz.core.v1.OracleService.Analyze:input_type -> defuzz.core.v1.OracleRequest
	12, // 14: defuzz.core.v1.CheckerMetadataService.ListCheckerMetadata:input_type -> defuzz.core.v1.ListCheckerMetadataRequest
	6,  // 15: defuzz.core.v1.BuildService.Build:output_type -> defuzz.core.v1.BuildResponse
	8,  // 16: defuzz.core.v1.CoverageService.Measure:output_type -> defuzz.core.v1.CoverageResponse
	10, // 17: defuzz.core.v1.OracleService.Analyze:output_type -> defuzz.core.v1.OracleResponse
	13, // 18: defuzz.core.v1.CheckerMetadataService.ListCheckerMetadata:output_type -> defuzz.core.v1.ListCheckerMetadataResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_oracle_proto_init() }
func file_oracle_proto_init() {
	if File_oracle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_oracle_proto_rawDesc), len(file_oracle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_oracle_proto_goTypes,
		DependencyIndexes: file_oracle_proto_depIdxs,
		EnumInfos:         file_oracle_proto_enumTypes,
		MessageInfos:      file_oracle_proto_msgTypes,
	}.Build()
	File_oracle_proto = out.File
	file_oracle_proto_goTypes = nil
	file_oracle_proto_depIdxs = nil
}
