# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import oracle_pb2 as oracle__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in oracle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BuildServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Build = channel.unary_unary(
                '/defuzz.core.v1.BuildService/Build',
                request_serializer=oracle__pb2.BuildRequest.SerializeToString,
                response_deserializer=oracle__pb2.BuildResponse.FromString,
                _registered_method=True)


class BuildServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Build(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuildServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Build': grpc.unary_unary_rpc_method_handler(
                    servicer.Build,
                    request_deserializer=oracle__pb2.BuildRequest.FromString,
                    response_serializer=oracle__pb2.BuildResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'defuzz.core.v1.BuildService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('defuzz.core.v1.BuildService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BuildService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Build(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/defuzz.core.v1.BuildService/Build',
            oracle__pb2.BuildRequest.SerializeToString,
            oracle__pb2.BuildResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoverageServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Measure = channel.unary_unary(
                '/defuzz.core.v1.CoverageService/Measure',
                request_serializer=oracle__pb2.CoverageRequest.SerializeToString,
                response_deserializer=oracle__pb2.CoverageResponse.FromString,
                _registered_method=True)


class CoverageServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Measure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoverageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Measure': grpc.unary_unary_rpc_method_handler(
                    servicer.Measure,
                    request_deserializer=oracle__pb2.CoverageRequest.FromString,
                    response_serializer=oracle__pb2.CoverageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'defuzz.core.v1.CoverageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('defuzz.core.v1.CoverageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoverageService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Measure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/defuzz.core.v1.CoverageService/Measure',
            oracle__pb2.CoverageRequest.SerializeToString,
            oracle__pb2.CoverageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OracleServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Analyze = channel.unary_unary(
                '/defuzz.core.v1.OracleService/Analyze',
                request_serializer=oracle__pb2.OracleRequest.SerializeToString,
                response_deserializer=oracle__pb2.OracleResponse.FromString,
                _registered_method=True)


class OracleServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Analyze(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OracleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Analyze': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyze,
                    request_deserializer=oracle__pb2.OracleRequest.FromString,
                    response_serializer=oracle__pb2.OracleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'defuzz.core.v1.OracleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('defuzz.core.v1.OracleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OracleService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Analyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/defuzz.core.v1.OracleService/Analyze',
            oracle__pb2.OracleRequest.SerializeToString,
            oracle__pb2.OracleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CheckerMetadataServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCheckerMetadata = channel.unary_unary(
                '/defuzz.core.v1.CheckerMetadataService/ListCheckerMetadata',
                request_serializer=oracle__pb2.ListCheckerMetadataRequest.SerializeToString,
                response_deserializer=oracle__pb2.ListCheckerMetadataResponse.FromString,
                _registered_method=True)


class CheckerMetadataServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListCheckerMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckerMetadataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCheckerMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCheckerMetadata,
                    request_deserializer=oracle__pb2.ListCheckerMetadataRequest.FromString,
                    response_serializer=oracle__pb2.ListCheckerMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'defuzz.core.v1.CheckerMetadataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('defuzz.core.v1.CheckerMetadataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CheckerMetadataService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListCheckerMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/defuzz.core.v1.CheckerMetadataService/ListCheckerMetadata',
            oracle__pb2.ListCheckerMetadataRequest.SerializeToString,
            oracle__pb2.ListCheckerMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
