// gRPC contract: 确定性节点 (build / coverage / oracle)
// 由 Python 编排器同步调用；Go 侧 internal/service/grpc_server.go 实现，
// 复用 internal/compiler、internal/coverage、internal/oracle，不改裁决逻辑。
//
// 设计要点：
// - 这三个 service 是确定性节点，绝不调用 agent（plan FR-002）。
// - CheckerMetadataService 暴露 SSOT 元数据只读视图，gRPC 与 MCP 共读同一份
//   internal/oracle/metadata.go（research R4）。
// - 覆盖率只在 CoverageService.Measure 强制测出（FR-022）。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.5
// source: oracle.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BuildService_Build_FullMethodName = "/defuzz.core.v1.BuildService/Build"
)

// BuildServiceClient is the client API for BuildService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildServiceClient interface {
	Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error)
}

type buildServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildServiceClient(cc grpc.ClientConnInterface) BuildServiceClient {
	return &buildServiceClient{cc}
}

func (c *buildServiceClient) Build(ctx context.Context, in *BuildRequest, opts ...grpc.CallOption) (*BuildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildResponse)
	err := c.cc.Invoke(ctx, BuildService_Build_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildServiceServer is the server API for BuildService service.
// All implementations must embed UnimplementedBuildServiceServer
// for forward compatibility.
type BuildServiceServer interface {
	Build(context.Context, *BuildRequest) (*BuildResponse, error)
	mustEmbedUnimplementedBuildServiceServer()
}

// UnimplementedBuildServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBuildServiceServer struct{}

func (UnimplementedBuildServiceServer) Build(context.Context, *BuildRequest) (*BuildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Build not implemented")
}
func (UnimplementedBuildServiceServer) mustEmbedUnimplementedBuildServiceServer() {}
func (UnimplementedBuildServiceServer) testEmbeddedByValue()                      {}

// UnsafeBuildServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildServiceServer will
// result in compilation errors.
type UnsafeBuildServiceServer interface {
	mustEmbedUnimplementedBuildServiceServer()
}

func RegisterBuildServiceServer(s grpc.ServiceRegistrar, srv BuildServiceServer) {
	// If the following call panics, it indicates UnimplementedBuildServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BuildService_ServiceDesc, srv)
}

func _BuildService_Build_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildServiceServer).Build(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BuildService_Build_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildServiceServer).Build(ctx, req.(*BuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildService_ServiceDesc is the grpc.ServiceDesc for BuildService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "defuzz.core.v1.BuildService",
	HandlerType: (*BuildServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Build",
			Handler:    _BuildService_Build_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}

const (
	CoverageService_Measure_FullMethodName = "/defuzz.core.v1.CoverageService/Measure"
)

// CoverageServiceClient is the client API for CoverageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoverageServiceClient interface {
	Measure(ctx context.Context, in *CoverageRequest, opts ...grpc.CallOption) (*CoverageResponse, error)
}

type coverageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoverageServiceClient(cc grpc.ClientConnInterface) CoverageServiceClient {
	return &coverageServiceClient{cc}
}

func (c *coverageServiceClient) Measure(ctx context.Context, in *CoverageRequest, opts ...grpc.CallOption) (*CoverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoverageResponse)
	err := c.cc.Invoke(ctx, CoverageService_Measure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoverageServiceServer is the server API for CoverageService service.
// All implementations must embed UnimplementedCoverageServiceServer
// for forward compatibility.
type CoverageServiceServer interface {
	Measure(context.Context, *CoverageRequest) (*CoverageResponse, error)
	mustEmbedUnimplementedCoverageServiceServer()
}

// UnimplementedCoverageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoverageServiceServer struct{}

func (UnimplementedCoverageServiceServer) Measure(context.Context, *CoverageRequest) (*CoverageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Measure not implemented")
}
func (UnimplementedCoverageServiceServer) mustEmbedUnimplementedCoverageServiceServer() {}
func (UnimplementedCoverageServiceServer) testEmbeddedByValue()                         {}

// UnsafeCoverageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoverageServiceServer will
// result in compilation errors.
type UnsafeCoverageServiceServer interface {
	mustEmbedUnimplementedCoverageServiceServer()
}

func RegisterCoverageServiceServer(s grpc.ServiceRegistrar, srv CoverageServiceServer) {
	// If the following call panics, it indicates UnimplementedCoverageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoverageService_ServiceDesc, srv)
}

func _CoverageService_Measure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoverageServiceServer).Measure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoverageService_Measure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoverageServiceServer).Measure(ctx, req.(*CoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoverageService_ServiceDesc is the grpc.ServiceDesc for CoverageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoverageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "defuzz.core.v1.CoverageService",
	HandlerType: (*CoverageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Measure",
			Handler:    _CoverageService_Measure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}

const (
	OracleService_Analyze_FullMethodName = "/defuzz.core.v1.OracleService/Analyze"
)

// OracleServiceClient is the client API for OracleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OracleServiceClient interface {
	Analyze(ctx context.Context, in *OracleRequest, opts ...grpc.CallOption) (*OracleResponse, error)
}

type oracleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOracleServiceClient(cc grpc.ClientConnInterface) OracleServiceClient {
	return &oracleServiceClient{cc}
}

func (c *oracleServiceClient) Analyze(ctx context.Context, in *OracleRequest, opts ...grpc.CallOption) (*OracleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OracleResponse)
	err := c.cc.Invoke(ctx, OracleService_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OracleServiceServer is the server API for OracleService service.
// All implementations must embed UnimplementedOracleServiceServer
// for forward compatibility.
type OracleServiceServer interface {
	Analyze(context.Context, *OracleRequest) (*OracleResponse, error)
	mustEmbedUnimplementedOracleServiceServer()
}

// UnimplementedOracleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOracleServiceServer struct{}

func (UnimplementedOracleServiceServer) Analyze(context.Context, *OracleRequest) (*OracleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedOracleServiceServer) mustEmbedUnimplementedOracleServiceServer() {}
func (UnimplementedOracleServiceServer) testEmbeddedByValue()                       {}

// UnsafeOracleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OracleServiceServer will
// result in compilation errors.
type UnsafeOracleServiceServer interface {
	mustEmbedUnimplementedOracleServiceServer()
}

func RegisterOracleServiceServer(s grpc.ServiceRegistrar, srv OracleServiceServer) {
	// If the following call panics, it indicates UnimplementedOracleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OracleService_ServiceDesc, srv)
}

func _OracleService_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OracleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OracleServiceServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OracleService_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OracleServiceServer).Analyze(ctx, req.(*OracleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OracleService_ServiceDesc is the grpc.ServiceDesc for OracleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OracleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "defuzz.core.v1.OracleService",
	HandlerType: (*OracleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Analyze",
			Handler:    _OracleService_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}

const (
	CheckerMetadataService_ListCheckerMetadata_FullMethodName = "/defuzz.core.v1.CheckerMetadataService/ListCheckerMetadata"
)

// CheckerMetadataServiceClient is the client API for CheckerMetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CheckerMetadataServiceClient interface {
	ListCheckerMetadata(ctx context.Context, in *ListCheckerMetadataRequest, opts ...grpc.CallOption) (*ListCheckerMetadataResponse, error)
}

type checkerMetadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckerMetadataServiceClient(cc grpc.ClientConnInterface) CheckerMetadataServiceClient {
	return &checkerMetadataServiceClient{cc}
}

func (c *checkerMetadataServiceClient) ListCheckerMetadata(ctx context.Context, in *ListCheckerMetadataRequest, opts ...grpc.CallOption) (*ListCheckerMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCheckerMetadataResponse)
	err := c.cc.Invoke(ctx, CheckerMetadataService_ListCheckerMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckerMetadataServiceServer is the server API for CheckerMetadataService service.
// All implementations must embed UnimplementedCheckerMetadataServiceServer
// for forward compatibility.
type CheckerMetadataServiceServer interface {
	ListCheckerMetadata(context.Context, *ListCheckerMetadataRequest) (*ListCheckerMetadataResponse, error)
	mustEmbedUnimplementedCheckerMetadataServiceServer()
}

// UnimplementedCheckerMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCheckerMetadataServiceServer struct{}

func (UnimplementedCheckerMetadataServiceServer) ListCheckerMetadata(context.Context, *ListCheckerMetadataRequest) (*ListCheckerMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCheckerMetadata not implemented")
}
func (UnimplementedCheckerMetadataServiceServer) mustEmbedUnimplementedCheckerMetadataServiceServer() {
}
func (UnimplementedCheckerMetadataServiceServer) testEmbeddedByValue() {}

// UnsafeCheckerMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckerMetadataServiceServer will
// result in compilation errors.
type UnsafeCheckerMetadataServiceServer interface {
	mustEmbedUnimplementedCheckerMetadataServiceServer()
}

func RegisterCheckerMetadataServiceServer(s grpc.ServiceRegistrar, srv CheckerMetadataServiceServer) {
	// If the following call panics, it indicates UnimplementedCheckerMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CheckerMetadataService_ServiceDesc, srv)
}

func _CheckerMetadataService_ListCheckerMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCheckerMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckerMetadataServiceServer).ListCheckerMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckerMetadataService_ListCheckerMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckerMetadataServiceServer).ListCheckerMetadata(ctx, req.(*ListCheckerMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckerMetadataService_ServiceDesc is the grpc.ServiceDesc for CheckerMetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckerMetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "defuzz.core.v1.CheckerMetadataService",
	HandlerType: (*CheckerMetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCheckerMetadata",
			Handler:    _CheckerMetadataService_ListCheckerMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle.proto",
}
